meta:
  title: "Uptime Kuma Security Policy | Vulnerability Reporting & Version Support"
  description: "Review the official Uptime Kuma security policy. Learn how to responsibly report security vulnerabilities and see supported version information to keep your instance secure."
sections:
  - sectionName: "securityPolicyHeader"
    sectionSummary: "A concise page header that introduces the core content of the security policy page, allowing users to immediately understand the page's topic."
    centeredHeroTitle: "Uptime Kuma Security Policy"
    centeredHeroDescription: "We take the security of our project very seriously. If you discover a security vulnerability, please follow the guidelines on this page to report it. We appreciate your help in keeping Uptime Kuma secure."
    centeredHeroActions:
      - text: "Report a Vulnerability"
        link: "https://github.com/louislam/uptime-kuma/security/advisories/new"
      - text: ""
        link: ""
  - sectionName: "vulnerabilityReportingGuide"
    sectionSummary: "Provides a clear, step-by-step guide for reporting vulnerabilities, including direct action links to ensure users can easily and correctly submit private reports."
    oneColumnGridTitle: "How to Report a Vulnerability"
    list:
      - sectionName: "reportStepOne"
        sectionSummary: "The first step of the reporting process: guiding users to submit vulnerabilities through the official GitHub Security Advisories channel and providing a direct link."
        ctaTitle: "Step 1: Submit via GitHub Security Advisories"
        ctaDescription: "This is the most important step! Please report issues privately through GitHub's official security channel to protect all users. Do not discuss them in the public issue tracker."
        cta:
          - text: "Report via GitHub Advisories"
            link: "https://github.com/louislam/uptime-kuma/security/advisories/new"
          - text: ""
            link: ""
      - sectionName: "reportStepTwo"
        sectionSummary: "The second step of the reporting process: reminding users to create an empty issue to ensure the maintainer is notified, as GitHub Advisories itself does not send notifications."
        ctaTitle: "Step 2: Create an Empty Security Issue as a Reminder"
        ctaDescription: "GitHub Advisories does not send notifications, so I might miss your report. It is very important that you also create an empty security issue to notify me!"
        cta:
          - text: "Create a Reminder Issue"
            link: "https://github.com/louislam/uptime-kuma/issues/new?assignees=&labels=help&template=security.md"
          - text: ""
            link: ""
  - sectionName: "bugBountyPolicy"
    sectionSummary: "Clearly states the project's stance on third-party bug bounty platforms to avoid confusion and potential risks."
    featureSectionTitle: "We Do Not Accept Third-Party Bug Bounty Platforms"
    featureSectionDescription: "At this time, I do not accept reports from other bug bounty platforms. In the past, people have attempted to send phishing links this way. To minimize my personal risk, please report exclusively through GitHub Advisories. I will ignore all emails from third-party bug bounty platforms."
    featureSectionBottomImage: ""
  - sectionName: "supportedVersions"
    sectionSummary: "Displays supported, deprecated, and unsupported Docker tags in a clear card grid to help users quickly confirm if their version is secure."
    fourColumnGridTitle: "Supported Versions and Tags"
    list:
      - sectionName: "tagOne"
        sectionSummary: "Displays the support status for the '1' tag."
        iconName: "lucide:check-circle-2"
        cardTitle: "1"
        cardDescription: "Supported"
      - sectionName: "tagOneDebian"
        sectionSummary: "Displays the support status for the '1-debian' tag."
        iconName: "lucide:check-circle-2"
        cardTitle: "1-debian"
        cardDescription: "Supported"
      - sectionName: "tagLatest"
        sectionSummary: "Displays the support status for the 'latest' tag."
        iconName: "lucide:check-circle-2"
        cardTitle: "latest"
        cardDescription: "Supported"
      - sectionName: "tagDebian"
        sectionSummary: "Displays the support status for the 'debian' tag."
        iconName: "lucide:check-circle-2"
        cardTitle: "debian"
        cardDescription: "Supported"
      - sectionName: "tagOneAlpine"
        sectionSummary: "Displays the deprecated status for the '1-alpine' tag."
        iconName: "lucide:alert-triangle"
        cardTitle: "1-alpine"
        cardDescription: "Deprecated"
      - sectionName: "tagAlpine"
        sectionSummary: "Displays the deprecated status for the 'alpine' tag."
        iconName: "lucide:alert-triangle"
        cardTitle: "alpine"
        cardDescription: "Deprecated"
      - sectionName: "tagOthers"
        sectionSummary: "Clearly states that all other tags are unsupported."
        iconName: "lucide:x-circle"
        cardTitle: "All Other Tags"
        cardDescription: "Unsupported"
      - sectionName: "upgradeRecommendation"
        sectionSummary: "Strongly recommends that users upgrade to the latest version to ensure security."
        iconName: "lucide:arrow-up-circle"
        cardTitle: "Stay Updated"
        cardDescription: "For security, please always use or upgrade to the latest version."