meta:
  title: "Uptime Kuma セキュリティポリシー | 脆弱性の報告とバージョンサポート"
  description: "Uptime Kumaの公式セキュリティポリシーをご覧ください。セキュリティ脆弱性を責任を持って報告する方法を学び、サポートされているバージョン情報を確認して、インスタンスの安全を確保してください。"
sections:
  - sectionName: "securityPolicyHeader"
    sectionSummary: "セキュリティポリシーページの核となる内容を紹介する簡潔なページタイトルで、ユーザーがすぐにページのテーマを理解できるようにします。"
    centeredHeroTitle: "Uptime Kuma セキュリティポリシー"
    centeredHeroDescription: "私たちはプロジェクトのセキュリティを非常に重視しています。セキュリティ脆弱性を発見した場合は、このページの指示に従って報告してください。Uptime Kumaの安全性を共に維持するためのご協力に感謝いたします。"
    centeredHeroActions:
      - text: "脆弱性を報告"
        link: "https://github.com/louislam/uptime-kuma/security/advisories/new"
      - text: ""
        link: ""
  - sectionName: "vulnerabilityReportingGuide"
    sectionSummary: "明確でステップバイステップの脆弱性報告ガイドを提供し、直接的なアクションリンクを含めることで、ユーザーが簡単かつ正確に非公開の報告を提出できるようにします。"
    oneColumnGridTitle: "脆弱性の報告方法"
    list:
      - sectionName: "reportStepOne"
        sectionSummary: "報告プロセスの第一歩：公式のGitHub Security Advisoriesチャネルを通じて脆弱性を提出するようユーザーを誘導し、直接リンクを提供します。"
        ctaTitle: "ステップ1：GitHub Security Advisoriesを通じて提出"
        ctaDescription: "これが最も重要なステップです！すべてのユーザーを保護するため、GitHubの公式セキュリティチャネルを通じて非公開で問題を報告してください。公開されている課題トラッカーで議論しないでください。"
        cta:
          - text: "GitHub Advisoriesで報告する"
            link: "https://github.com/louislam/uptime-kuma/security/advisories/new"
          - text: ""
            link: ""
      - sectionName: "reportStepTwo"
        sectionSummary: "報告プロセスの第二歩：GitHub Advisories自体は通知を送信しないため、メンテナーが通知を受け取れるように、空のIssueを作成するようユーザーに促します。"
        ctaTitle: "ステップ2：通知用に空のセキュリティIssueを作成"
        ctaDescription: "GitHub Advisoriesは能動的に通知を送信しないため、あなたの報告を見逃す可能性があります。私に通知するために、追加で空のセキュリティIssueを作成してください。これは非常に重要です！"
        cta:
          - text: "通知用のIssueを作成"
            link: "https://github.com/louislam/uptime-kuma/issues/new?assignees=&labels=help&template=security.md"
          - text: ""
            link: ""
  - sectionName: "bugBountyPolicy"
    sectionSummary: "サードパーティの脆弱性報奨金プラットフォームに対するプロジェクトの立場を明確にし、混乱や潜在的なリスクを回避します。"
    featureSectionTitle: "サードパーティの脆弱性報奨金プラットフォームは受け付けていません"
    featureSectionDescription: "現在、他の脆弱性報奨金プラットフォームからの報告は受け付けていません。過去にこの方法でフィッシングリンクを送信しようとする試みがあったため、私個人のリスクを最小限に抑えるためにも、必ずGitHub Advisoriesを通じてのみ報告してください。サードパーティの脆弱性報奨金プラットフォームからのメールはすべて無視します。"
    featureSectionBottomImage: ""
  - sectionName: "supportedVersions"
    sectionSummary: "サポート対象、非推奨、およびサポート対象外のDockerタグを明確なカードグリッドで表示し、ユーザーが自分のバージョンが安全かどうかを迅速に確認できるようにします。"
    fourColumnGridTitle: "サポートされているバージョンとタグ"
    list:
      - sectionName: "tagOne"
        sectionSummary: "'1' タグのサポート状況を表示します。"
        iconName: "lucide:check-circle-2"
        cardTitle: "1"
        cardDescription: "サポート対象"
      - sectionName: "tagOneDebian"
        sectionSummary: "'1-debian' タグのサポート状況を表示します。"
        iconName: "lucide:check-circle-2"
        cardTitle: "1-debian"
        cardDescription: "サポート対象"
      - sectionName: "tagLatest"
        sectionSummary: "'latest' タグのサポート状況を表示します。"
        iconName: "lucide:check-circle-2"
        cardTitle: "latest"
        cardDescription: "サポート対象"
      - sectionName: "tagDebian"
        sectionSummary: "'debian' タグのサポート状況を表示します。"
        iconName: "lucide:check-circle-2"
        cardTitle: "debian"
        cardDescription: "サポート対象"
      - sectionName: "tagOneAlpine"
        sectionSummary: "'1-alpine' タグの非推奨状況を表示します。"
        iconName: "lucide:alert-triangle"
        cardTitle: "1-alpine"
        cardDescription: "非推奨"
      - sectionName: "tagAlpine"
        sectionSummary: "'alpine' タグの非推奨状況を表示します。"
        iconName: "lucide:alert-triangle"
        cardTitle: "alpine"
        cardDescription: "非推奨"
      - sectionName: "tagOthers"
        sectionSummary: "他のすべてのタグがサポートされていないことを明確に示します。"
        iconName: "lucide:x-circle"
        cardTitle: "その他すべてのタグ"
        cardDescription: "サポート対象外"
      - sectionName: "upgradeRecommendation"
        sectionSummary: "セキュリティを確保するため、最新バージョンへのアップグレードを強く推奨します。"
        iconName: "lucide:arrow-up-circle"
        cardTitle: "最新の状態を維持"
        cardDescription: "セキュリティのため、常に最新バージョンを使用またはアップグレードしてください。"